image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf build # remove the existing build
  - CI=false npm install # install required packages

stages:
  - audit

script:
  - echo "Audit Stage"

audit: 
    stage: audit
    script: npm audit

script:
    - echo "Build stage"