image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf build # remove the existing build
  - CI=false npm install # install required packages

stages:
  - audit
  - build
  - production

audit:
  stage: audit
  script:
    - npm audit

build:
  stage: build
  script:
    - rm -rf node_modules
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/

deploy:
  stage: production
  script:
    - rm -rf node_modules
    - yarn install
    - yarn build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
