image: node@latest

  stages:
    - build
    - lint
    - test
    - production

    script:
    - echo "Build stage"

    build: 
      stage: build
      - npm install
      - npm build
      artifacts:
        paths:
         - build/

    script:
    - echo "Deploying to production server"

    deploy: 
      stage: production
      script:
      - npm install
      - npm run build
      - rm -rf public
      - mv build public
      artifacts:
        paths:
        - public

