image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf build # remove the existing build
  - CI=false npm install # install required packages

stages:
  - build
  - lint
  - test
  - production

build:
  stage: build
  script:
    - rm -rf node_modules
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

lint:
  stage: lint
  script:
    - npm run lint:ci

test:
  stage: test
  script:
    - npm run test:ci

deploy:
  stage: production
  script:
    - rm -rf node_modules
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
