image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf build # remove the existing build
  - CI=false npm install # install required packages

stages:
  - audit

script:
  - echo "Audit Stage"

audit: 
    stage: audit
    script: 
        - npm audit

script:
    - echo "Build stage"

build: 
    stage: build
    script: 
    - npm install
    - npm build
    artifacts:
      paths:
        - build/

    script:
    - echo "Deploying to production server"

    deploy: 
    stage: production
    script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
    artifacts:
      paths:
      - public

